/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package farmacia;

/**
 *
 * @author gabriel
 */
public class NewJFrame1 extends javax.swing.JFrame {

    private String medicamento;
    private String cantidad;
    private String tipo;
    private String distribuidor;
    private String farmacia;

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1(String medicamento, String cantidad, String tipo, String distribuidor, String farmacia) {
        this.medicamento = medicamento;
        this.cantidad = cantidad;
        this.tipo = tipo;
        this.distribuidor = distribuidor;
        this.farmacia = farmacia;
        initComponents();
        medicamentoEscogido.setText(medicamento);
        cantidadEscogida.setText(cantidad);
        tipoEscogido.setText(tipo);
        distribuidoraEscogida.setText(distribuidor);
        farmaciaEscogida.setText(farmacia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medicamentoEscogido = new javax.swing.JLabel();
        cantidadEscogida = new javax.swing.JLabel();
        tipoEscogido = new javax.swing.JLabel();
        distribuidoraEscogida = new javax.swing.JLabel();
        farmaciaEscogida = new javax.swing.JLabel();
        medicamentoEscogido1 = new javax.swing.JLabel();
        medicamentoEscogido2 = new javax.swing.JLabel();
        medicamentoEscogido3 = new javax.swing.JLabel();
        medicamentoEscogido4 = new javax.swing.JLabel();
        medicamentoEscogido5 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        medicamentoEscogido.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        medicamentoEscogido.setText("jLabel1");

        cantidadEscogida.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        cantidadEscogida.setText("jLabel2");

        tipoEscogido.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        tipoEscogido.setText("jLabel3");

        distribuidoraEscogida.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        distribuidoraEscogida.setText("jLabel3");

        farmaciaEscogida.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        farmaciaEscogida.setText("jLabel3");

        medicamentoEscogido1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        medicamentoEscogido1.setText("Medicamento");

        medicamentoEscogido2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        medicamentoEscogido2.setText("Tipo");

        medicamentoEscogido3.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        medicamentoEscogido3.setText("Farmacia a recoger");

        medicamentoEscogido4.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        medicamentoEscogido4.setText("Cantidad");

        medicamentoEscogido5.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        medicamentoEscogido5.setText("Distribuidora");

        jToggleButton1.setText("Confirmar pedido");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jButton1.setText("Corregir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medicamentoEscogido4)
                    .addComponent(medicamentoEscogido1)
                    .addComponent(medicamentoEscogido2)
                    .addComponent(medicamentoEscogido5)
                    .addComponent(medicamentoEscogido3)
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medicamentoEscogido)
                    .addComponent(cantidadEscogida)
                    .addComponent(tipoEscogido)
                    .addComponent(distribuidoraEscogida)
                    .addComponent(farmaciaEscogida)
                    .addComponent(jButton1))
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicamentoEscogido)
                    .addComponent(medicamentoEscogido1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadEscogida)
                    .addComponent(medicamentoEscogido4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipoEscogido)
                    .addComponent(medicamentoEscogido2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medicamentoEscogido5)
                    .addComponent(distribuidoraEscogida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(farmaciaEscogida)
                    .addComponent(medicamentoEscogido3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame2().setVisible(true);
            }
        });
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal(medicamento, cantidad).setVisible(true);
                System.out.println(medicamento
                );
                
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cantidadEscogida;
    private javax.swing.JLabel distribuidoraEscogida;
    private javax.swing.JLabel farmaciaEscogida;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel medicamentoEscogido;
    private javax.swing.JLabel medicamentoEscogido1;
    private javax.swing.JLabel medicamentoEscogido2;
    private javax.swing.JLabel medicamentoEscogido3;
    private javax.swing.JLabel medicamentoEscogido4;
    private javax.swing.JLabel medicamentoEscogido5;
    private javax.swing.JLabel tipoEscogido;
    // End of variables declaration//GEN-END:variables
}
