package farmacia;

import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.List;
import javax.swing.JList;
import javax.swing.JPopupMenu;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author gabriel
 */
public class Principal extends javax.swing.JFrame {

    public void setMedicamento(String medicamento) {
        this.medicamento.setText(medicamento);
    }

    /**
     * Creates new form NewJFrame
     */
    static String medicina;
    static String Quecantidad;
    JPopupMenu popupMenu = new JPopupMenu();

    public Principal(String medincina, String cantidad) {
        initComponents();

    }

    private boolean esNumero(String texto) {
        return texto.matches("\\d*");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medicamento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TipoMedicamento = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        errCantidad = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dist1 = new javax.swing.JRadioButton();
        dist2 = new javax.swing.JRadioButton();
        dist3 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        Realizar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Farm1 = new javax.swing.JCheckBox();
        Farm2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        medicamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                medicamentoFocusLost(evt);
            }
        });
        medicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicamentoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre medicamento");

        TipoMedicamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Analgésico", "Analéptico", "Anestésico", "Antiácido", "Antidepresivo", "Antibióticos"}));
        TipoMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoMedicamentoActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmacia/images/descarga.png"))); // NOI18N

        cantidad.setSelectionColor(new java.awt.Color(255, 51, 51));
        cantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidadFocusLost(evt);
            }
        });
        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });

        jLabel3.setText("Cantidad");

        errCantidad.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N

        jLabel4.setText("Distribuidor");

        dist1.setText("Cofarma");
        dist1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dist1ActionPerformed(evt);
            }
        });

        dist2.setText("Empsephar");
        dist2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dist2ActionPerformed(evt);
            }
        });

        dist3.setText("Cemefar");
        dist3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dist3ActionPerformed(evt);
            }
        });

        Realizar.setText("Realizar Pedido");
        Realizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Farm1.setText("Farmacia Principal");
        Farm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Farm1ActionPerformed(evt);
            }
        });

        Farm2.setText("Farmacia Secundaria");
        Farm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Farm2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(338, 338, 338))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(TipoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medicamento)
                            .addComponent(cantidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(errCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(323, 323, 323)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addGap(53, 53, 53)
                                        .addComponent(Realizar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dist1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dist2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dist3)))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Farm2)
                                    .addComponent(Farm1))))
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(medicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(TipoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(errCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dist1)
                    .addComponent(dist2)
                    .addComponent(dist3)
                    .addComponent(Farm1))
                .addGap(26, 26, 26)
                .addComponent(Farm2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Realizar)
                    .addComponent(jButton2))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TipoMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoMedicamentoActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_TipoMedicamentoActionPerformed

    private void medicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicamentoActionPerformed
        // TODO add your handling code here:
        medicamento.setText(medicina);


    }//GEN-LAST:event_medicamentoActionPerformed

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        String input = cantidad.getText();
        // Verifica si la entrada contiene solo números y su longitud no excede 4 caracteres
        if (input.matches("\\d+") && input.length() <= 4) {
            // Aquí puedes realizar cualquier acción que necesites con el texto válido
            System.out.println("Texto válido: " + input);
            errCantidad.setText("");
        } else {
            // Si la entrada no es válida, muestra un mensaje de error
            errCantidad.setForeground(Color.red);
            if (!input.matches("\\d+")) {
                errCantidad.setText("Debe ser un número la cantidad");
            } else {
                errCantidad.setText("Introduzca una cantidad válida (máximo 4 dígitos)");
            }
            cantidad.setSelectionColor(Color.red);
            cantidad.setText("");
        }

    }//GEN-LAST:event_cantidadActionPerformed


    private void dist1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dist1ActionPerformed

        if (dist1.isSelected()) {
            dist2.setSelected(false);
            dist3.setSelected(false);
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmacia/images/Cofarma.png")));
            cantidad.setBackground(Color.white);
            errCantidad.setText("");
        }
    }//GEN-LAST:event_dist1ActionPerformed

    private void dist2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dist2ActionPerformed
        // TODO add your handling code here:
        if (dist2.isSelected()) {
            dist1.setSelected(false);
            dist3.setSelected(false);
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmacia/images/Empsephar.jpeg")));
            errCantidad.setText("");
        }
    }//GEN-LAST:event_dist2ActionPerformed

    private void dist3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dist3ActionPerformed
        // TODO add your handling code here:
        if (dist3.isSelected()) {
            dist2.setSelected(false);
            dist1.setSelected(false);
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmacia/images/Cemefar.png")));
            errCantidad.setText("");
        }
    }//GEN-LAST:event_dist3ActionPerformed

    private void RealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarActionPerformed

        final String medi = medicamento.getText();
        final String canti = cantidad.getText();
        final String tipo = TipoMedicamento.getSelectedItem().toString();

        String distribuidor;
        String farmacia;

        if (dist1.isSelected()) {
            distribuidor = "Cofarma";
        } else if (dist2.isSelected()) {
            distribuidor = "Empsephar";
        } else if (dist3.isSelected()) {
            distribuidor = "Cemefar";
        } else {
            distribuidor = null;
        }

        if (Farm1.isSelected()) {
            farmacia = "Farmacia principal";
        } else if (Farm2.isSelected()) {
            farmacia = "Farmacia secundaria";
        } else {
            farmacia = null; // Tratar el caso en que no se ha seleccionado una farmacia
        }

        if (medi.length() == 0) {
            errCantidad.setText("Debe de indicar un medicamento");
        } else if (canti.length() == 0) {
            errCantidad.setText("Debe de indicar una cantidad");

        } else if (tipo.equals("Seleccione")) {
            errCantidad.setText("Debe de seleccionar un tipo");
        } else if (distribuidor == null) {
            errCantidad.setText("Debe seleccionar un distribuidor");
        } else if (farmacia == null) {
            errCantidad.setText("Debe seleccionar una farmacia");
        } else if (errCantidad.getText().length() > 0) {

        } else {
            dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    NewJFrame1 frame = new NewJFrame1(medi, canti, tipo, distribuidor, farmacia);
                    frame.setVisible(true);

                }
            });

        }

    }//GEN-LAST:event_RealizarActionPerformed

    private void Farm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Farm1ActionPerformed
        // TODO add your handling code here:
        if (Farm1.isSelected()) {
            Farm2.setSelected(false);
        }
    }//GEN-LAST:event_Farm1ActionPerformed

    private void Farm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Farm2ActionPerformed
        // TODO add your handling code here:
        if (Farm2.isSelected()) {
            Farm1.setSelected(false);
        }
    }//GEN-LAST:event_Farm2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidadFocusLost
        // TODO add your handling code here:
        String input = cantidad.getText();
        if (input.matches("\\d+") && input.length() <= 4) {
            System.out.println("Texto válido: " + input);
            errCantidad.setText("");
        } else {
            errCantidad.setForeground(Color.red);
            if (!input.matches("\\d+")) {
                errCantidad.setText("La cantidad debe de ser un número");
            } else {
                errCantidad.setText("Introduzca una cantidad válida (máximo 4 dígitos)");
            }
            cantidad.setSelectionColor(Color.red);
            cantidad.setText("");
            
        }
    }//GEN-LAST:event_cantidadFocusLost

    private void medicamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_medicamentoFocusLost

        if(medicamento.getText().length()>10){
            errCantidad.setText("Demasiado largo");
            medicamento.setText("");
        }
        if (medicamento.getText().matches(".*[^a-zA-Z].*")) {
        errCantidad.setText("Contiene caracteres no permitidos");
        medicamento.setText("");
    }
    }//GEN-LAST:event_medicamentoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        String medicina = "NombreMedicina";
        String Quecantidad = "Cantidad";
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal(medicina, Quecantidad).setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Farm1;
    private javax.swing.JCheckBox Farm2;
    private javax.swing.JButton Realizar;
    private javax.swing.JComboBox<String> TipoMedicamento;
    private javax.swing.JTextField cantidad;
    private javax.swing.JRadioButton dist1;
    private javax.swing.JRadioButton dist2;
    private javax.swing.JRadioButton dist3;
    private javax.swing.JLabel errCantidad;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField medicamento;
    // End of variables declaration//GEN-END:variables
}
