package farmacia;

import java.awt.Color;

/**
 *
 * @author gabriel
 */
public class Principal extends javax.swing.JFrame {

    public void setMedicamento(String medicamento) {
        this.medicamento.setText(medicamento);
    }

    /**
     * Creates new form NewJFrame
     */
    static String medicina;

    public Principal(String medincina, String cantidad) {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medicamento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TipoMedicamento = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mensajeError = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dist1 = new javax.swing.JRadioButton();
        dist2 = new javax.swing.JRadioButton();
        dist3 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        Realizar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        Farm1 = new javax.swing.JCheckBox();
        Farm2 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        medicamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                medicamentoFocusLost(evt);
            }
        });
        medicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicamentoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre medicamento");

        TipoMedicamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Analgésico", "Analéptico", "Anestésico", "Antiácido", "Antidepresivo", "Antibióticos"}));
        TipoMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoMedicamentoActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmacia/images/descarga.png"))); // NOI18N

        cantidad.setSelectionColor(new java.awt.Color(255, 51, 51));
        cantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidadFocusLost(evt);
            }
        });
        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });

        jLabel3.setText("Cantidad");

        mensajeError.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N

        jLabel4.setText("Distribuidor");

        dist1.setText("Cofarma");
        dist1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dist1ActionPerformed(evt);
            }
        });

        dist2.setText("Empsephar");
        dist2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dist2ActionPerformed(evt);
            }
        });

        dist3.setText("Cemefar");
        dist3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dist3ActionPerformed(evt);
            }
        });

        Realizar.setText("Realizar Pedido");
        Realizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        Farm1.setText("Farmacia Principal");
        Farm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Farm1ActionPerformed(evt);
            }
        });

        Farm2.setText("Farmacia Secundaria");
        Farm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Farm2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo de medicamento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(338, 338, 338))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addComponent(TipoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(medicamento)
                                .addComponent(cantidad))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(mensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(323, 323, 323)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonSalir)
                                        .addGap(53, 53, 53)
                                        .addComponent(Realizar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dist1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dist2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dist3)))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Farm2)
                                    .addComponent(Farm1))))
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(medicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TipoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(mensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dist1)
                    .addComponent(dist2)
                    .addComponent(dist3)
                    .addComponent(Farm1))
                .addGap(26, 26, 26)
                .addComponent(Farm2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Realizar)
                    .addComponent(botonSalir))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TipoMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoMedicamentoActionPerformed
    }//GEN-LAST:event_TipoMedicamentoActionPerformed

    private void medicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicamentoActionPerformed
        medicamento.setText(medicina);
    }//GEN-LAST:event_medicamentoActionPerformed

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed


    }//GEN-LAST:event_cantidadActionPerformed


    private void dist1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dist1ActionPerformed
        if (dist1.isSelected()) {
            dist2.setSelected(false);
            dist3.setSelected(false);
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmacia/images/Cofarma.png")));
            cantidad.setBackground(Color.white);
            mensajeError.setText("");
        }
    }//GEN-LAST:event_dist1ActionPerformed

    private void dist2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dist2ActionPerformed
        if (dist2.isSelected()) {
            dist1.setSelected(false);
            dist3.setSelected(false);
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmacia/images/Empsephar.jpeg")));
            mensajeError.setText("");
        }
    }//GEN-LAST:event_dist2ActionPerformed

    private void dist3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dist3ActionPerformed
        if (dist3.isSelected()) {
            dist2.setSelected(false);
            dist1.setSelected(false);
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmacia/images/Cemefar.png")));
            mensajeError.setText("");
        }
    }//GEN-LAST:event_dist3ActionPerformed

    private void RealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarActionPerformed

        final String medi = medicamento.getText();
        final String canti = cantidad.getText();
        final String tipo = TipoMedicamento.getSelectedItem().toString();
        String distribuidor;
        String farmacia;

        if (dist1.isSelected()) {
            distribuidor = "Cofarma";
        } else if (dist2.isSelected()) {
            distribuidor = "Empsephar";
        } else if (dist3.isSelected()) {
            distribuidor = "Cemefar";
        } else {
            distribuidor = null;
        }
        if ((Farm2.isSelected() && Farm1.isSelected())) {
            farmacia = "Farmacia principal y secundaria ";
        } else if (Farm2.isSelected()) {
            farmacia = "Farmacia secundaria";
        } else if (Farm1.isSelected()) {
            farmacia = "Farmacia principal";
        } else {
            farmacia = null;
        }

        if (medi.length() == 0) {
            mensajeError.setText("Debe de indicar un medicamento");
        } else if (canti.length() == 0) {
            mensajeError.setText("Debe de indicar una cantidad");

        } else if (!canti.matches("\\d+")) {
            mensajeError.setText("La cantidad debe de ser un número");
        } else if (Integer.parseInt(canti) > 20) {
            mensajeError.setText("Introduzca una cantidad válida (máximo 20 medicamentos)");
        } else if (medicamento.getText().length() > 20) {
            mensajeError.setText("Demasiado largo el nombre del medicamento");
            mensajeError.setForeground(Color.RED);
        } else if (medicamento.getText().matches(".*[^a-zA-Z 0-9].*")) {
            mensajeError.setText("El campo Medicamento contiene caracteres no permitidos");
            mensajeError.setForeground(Color.RED);
        } else if (tipo.equals("Seleccione")) {
            mensajeError.setText("Debe de seleccionar un tipo");
        } else if (distribuidor == null) {
            mensajeError.setText("Debe seleccionar un distribuidor");
        } else if (farmacia == null) {
            mensajeError.setText("Debe seleccionar una farmacia");
        } else if (mensajeError.getText().length() > 0) {

        } else {
            setVisible(false);
            VerificacionPedido verificacionPedido = new VerificacionPedido(medi, canti, tipo, distribuidor, farmacia);
            verificacionPedido.setPrincipal(this);
            verificacionPedido.setVisible(true);
        }

    }//GEN-LAST:event_RealizarActionPerformed

    private void Farm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Farm1ActionPerformed
        if (Farm1.isSelected()) {
            mensajeError.setText("");
        }
    }//GEN-LAST:event_Farm1ActionPerformed

    private void Farm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Farm2ActionPerformed
        if (Farm2.isSelected()) {
            mensajeError.setText("");
        }
    }//GEN-LAST:event_Farm2ActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void cantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidadFocusLost
        mensajeError.setText("");
    }//GEN-LAST:event_cantidadFocusLost

    private void medicamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_medicamentoFocusLost
        mensajeError.setText("");
    }//GEN-LAST:event_medicamentoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        String medicina = "NombreMedicina";
        String Quecantidad = "Cantidad";
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal(medicina, Quecantidad).setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Farm1;
    private javax.swing.JCheckBox Farm2;
    private javax.swing.JButton Realizar;
    private javax.swing.JComboBox<String> TipoMedicamento;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField cantidad;
    private javax.swing.JRadioButton dist1;
    private javax.swing.JRadioButton dist2;
    private javax.swing.JRadioButton dist3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField medicamento;
    private javax.swing.JLabel mensajeError;
    // End of variables declaration//GEN-END:variables
}
