
package farmacia;

/**
 *
 * @author gabriel
 */
public class VerificacionPedido extends javax.swing.JFrame {

    private String medicamento;
    private String cantidad;
    private String tipo;
    private String distribuidor;
    private String farmacia;

        private Principal principal;

    public void setPrincipal(Principal principal) {
        this.principal = principal;
    }
    /**
     * Creates new form NewJFrame1
     */
    public VerificacionPedido(String medicamento, String cantidad, String tipo, String distribuidor, String farmacia) {
        this.medicamento = medicamento;
        this.cantidad = cantidad;
        this.tipo = tipo;
        this.distribuidor = distribuidor;
        this.farmacia = farmacia;
        initComponents();
        escogidoMedicamento.setText(medicamento);
        escogidoCantidad.setText(cantidad);
        escogidoTipo.setText(tipo);
        escogidoDistribuidora.setText(distribuidor);
        EscogidoFarmacia.setText(farmacia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escogidoMedicamento = new javax.swing.JLabel();
        escogidoCantidad = new javax.swing.JLabel();
        escogidoTipo = new javax.swing.JLabel();
        escogidoDistribuidora = new javax.swing.JLabel();
        EscogidoFarmacia = new javax.swing.JLabel();
        estaticoMedicamento = new javax.swing.JLabel();
        estaticoTipo = new javax.swing.JLabel();
        estaticoFarmacia = new javax.swing.JLabel();
        estaticoCantidad = new javax.swing.JLabel();
        estaticoDistribuidora = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escogidoMedicamento.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        escogidoMedicamento.setText("jLabel1");

        escogidoCantidad.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        escogidoCantidad.setText("jLabel2");

        escogidoTipo.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        escogidoTipo.setText("jLabel3");

        escogidoDistribuidora.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        escogidoDistribuidora.setText("jLabel3");

        EscogidoFarmacia.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        EscogidoFarmacia.setText("jLabel3");

        estaticoMedicamento.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        estaticoMedicamento.setText("Medicamento");

        estaticoTipo.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        estaticoTipo.setText("Tipo");

        estaticoFarmacia.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        estaticoFarmacia.setText("Farmacia");

        estaticoCantidad.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        estaticoCantidad.setText("Cantidad");

        estaticoDistribuidora.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        estaticoDistribuidora.setText("Distribuidora");

        jToggleButton1.setText("Confirmar pedido");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jButton1.setText("Corregir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estaticoCantidad)
                    .addComponent(estaticoMedicamento)
                    .addComponent(estaticoTipo)
                    .addComponent(estaticoDistribuidora)
                    .addComponent(estaticoFarmacia)
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(escogidoMedicamento)
                    .addComponent(escogidoCantidad)
                    .addComponent(escogidoTipo)
                    .addComponent(escogidoDistribuidora)
                    .addComponent(EscogidoFarmacia)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(escogidoMedicamento)
                    .addComponent(estaticoMedicamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(escogidoCantidad)
                    .addComponent(estaticoCantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(escogidoTipo)
                    .addComponent(estaticoTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estaticoDistribuidora)
                    .addComponent(escogidoDistribuidora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EscogidoFarmacia)
                    .addComponent(estaticoFarmacia))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        System.out.println("Pedido de " + cantidad + " " + medicamento + 
                " del tipo "+ tipo + " de " + distribuidor + " para " + farmacia + "\nConfirmado");
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame2().setVisible(true);
            }
        });
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if (principal != null) {
            principal.setVisible(true);
        }
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerificacionPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerificacionPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerificacionPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerificacionPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EscogidoFarmacia;
    private javax.swing.JLabel escogidoCantidad;
    private javax.swing.JLabel escogidoDistribuidora;
    private javax.swing.JLabel escogidoMedicamento;
    private javax.swing.JLabel escogidoTipo;
    private javax.swing.JLabel estaticoCantidad;
    private javax.swing.JLabel estaticoDistribuidora;
    private javax.swing.JLabel estaticoFarmacia;
    private javax.swing.JLabel estaticoMedicamento;
    private javax.swing.JLabel estaticoTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
